version: '3.8'

services:
  caldav-dashboard:
    build: .
    ports:
      - "3002:3000"
    environment:
      - CALDAV_URL=${CALDAV_URL}
      - CALDAV_USER=${CALDAV_USER}
      - CALDAV_PASSWORD=${CALDAV_PASSWORD}
      - PORT=${PORT:-3000}
      - TZ=${TZ:-Europe/Berlin}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
